apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payroll-payment-orchestrator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payroll-payment-orchestrator
