apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-payment-orchestrator
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: payroll-orchestrator
      containers:
        - name: application
          volumeMounts:
            - name: key-vault-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: key-vault-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: payroll-orchestrator-key-vault
